#!/bin/sh
# THE whisper gateway config, written from ONE place.
#
# `scripts/whisper-setup.sh` used to be the only thing that wrote
# `whisper-models/llama-swap.yaml`, and it is a host script run with sudo — which on this
# deployment means it is a script the owner cannot run at all (CLAUDE.md #10, and §10.4ab's
# argument for every other setting). An update never regenerated it either, so a flag added to
# the repo reached a live box only if somebody re-ran the provisioner by hand.
#
# So the generation lives here and BOTH callers use it: the provisioner after it downloads a
# model, and `update-inner.sh` on every update. That is deliberately the lesson written at the
# top of `update-inner.sh` — "It is one file because it was two, and they drifted" — applied
# before it happens rather than after.
#
#   sh deploy/whisper-config.sh <models-dir> [gpu]
#
# NO `--language` HERE, deliberately: this server is shared with the agent's transcribe tool,
# which is handed recordings in whatever language they were made in. The room panel passes
# `language=en` as a per-request field instead, where the assumption is true.
#
# `gpu` is "true" or "false"; anything else is false. It decides one flag, `--no-gpu`, which is
# only meaningful because `Dockerfile.tts-stt` now builds whisper.cpp with Vulkan — so the
# choice is a config line rather than a rebuild, and llama-swap's `--watch-config` picks it up
# without restarting the container.
#
# SAFE TO RUN WHEN WHISPER IS NOT PROVISIONED, which is the property that lets an update call
# it unconditionally: no model file means no config is written and nothing is touched. The
# model filename is DISCOVERED rather than assumed, so a box on `base.en` is not silently
# repointed at a model it does not have.
set -eu

DIR="${1:?usage: whisper-config.sh <models-dir> [gpu]}"
GPU="${2:-false}"

[ -d "$DIR" ] || exit 0

# Whichever ggml model is actually on disk. More than one is not an error — prefer the largest,
# which is the one a deliberate provision left there.
GGML=""
BEST=0
for f in "$DIR"/ggml-*.bin; do
  [ -f "$f" ] || continue
  sz=$(wc -c < "$f" 2>/dev/null || echo 0)
  if [ "$sz" -gt "$BEST" ]; then
    BEST="$sz"
    GGML="$(basename "$f")"
  fi
done
[ -n "$GGML" ] || exit 0

NOGPU="      --no-gpu"
if [ "$GPU" = "true" ]; then
  NOGPU=""
fi

# Written to a temp file and moved into place. llama-swap watches this path, so a partial
# write is a config it may read mid-line — and the failure mode of that is no transcription at
# all on a box nobody can shell into.
TMP="$DIR/.llama-swap.yaml.$$"
cat > "$TMP" <<EOF
# Generated by deploy/whisper-config.sh — do not edit by hand.
# Regenerated on every update, so a change to that script reaches this box.
healthCheckTimeout: 300
models:
  whisper:
    proxy: http://127.0.0.1:9200
    # whisper-server isn't a llama-server, so llama-swap's default /health probe does not
    # gate it; poll GET / (returns 200) until the model finishes loading before forwarding.
    checkEndpoint: /
    cmd: >
      whisper-server --host 127.0.0.1 --port 9200
      --model /models/$GGML
      --inference-path /v1/audio/transcriptions
      --convert
$NOGPU
    ttl: 300
EOF
mv -f "$TMP" "$DIR/llama-swap.yaml"
echo "[whisper-config] $GGML, gpu=$GPU"
