#!/usr/bin/env bash
# OPT-IN: provision self-hosted local models and enable the feature.
#
#   sudo bash scripts/local-llm-setup.sh                 # recommended set
#   sudo bash scripts/local-llm-setup.sh qwen3-vl-30b    # explicit ids
#
# Tuned for an AMD Strix Halo box (Ryzen AI Max+ 395). This is NEVER run by the
# default install or by dev-setup.sh — it downloads tens of GB of weights and
# starts a GPU service, so it is a deliberate, separate step. It:
#   1. resolves the chosen catalog models (jbrain.llm.local_catalog),
#   2. downloads their GGUF weights into ./local-models,
#   3. writes a llama-swap config fronting them on one OpenAI endpoint,
#   4. flips JBRAIN_LOCAL_LLM_ENABLED + LOCAL_MODELS on in .env and starts the
#      `local-llm` compose profile.
#
# Run from the install dir (/opt/jbrain2) where docker-compose.yml + .env live.
set -euo pipefail

INSTALL_DIR="${JBRAIN_INSTALL_DIR:-/opt/jbrain2}"
MODELS_DIR="$INSTALL_DIR/local-models"
cd "$INSTALL_DIR"

say() { printf '\n[local-llm] %s\n' "$*"; }

[ -f .env ] || { echo "No .env in $INSTALL_DIR — run deploy/install.sh first." >&2; exit 1; }

# Best-effort GPU sanity check: Vulkan needs /dev/dri. Warn, don't block — the
# operator may know better (remote build host, different AMD part).
if [ ! -e /dev/dri ]; then
  say "WARNING: /dev/dri not found — the Vulkan gateway needs an AMD GPU. Continuing anyway."
fi

IDS=("$@")
if [ ${#IDS[@]} -eq 0 ]; then
  say "No models named; using the recommended set"
  mapfile -t IDS < <(docker compose run --rm -T api python -c \
    "from jbrain.llm import local_catalog; print('\n'.join(local_catalog.recommended_ids()))")
fi
say "Selected models: ${IDS[*]}"

# The catalog is the single source of truth — read its JSON manifest from the
# api image so the script never hard-codes repos or filenames.
MANIFEST="$(docker compose run --rm -T api python -m jbrain.llm.local_catalog "${IDS[@]}")"

mkdir -p "$MODELS_DIR"

# Download weights with the official huggingface_hub CLI in a throwaway
# container; only the --include globs from the manifest are pulled.
say "Downloading weights into $MODELS_DIR (this can take a while)"
echo "$MANIFEST" | docker run --rm -i -v "$MODELS_DIR:/models" python:3.11-slim bash -c '
  set -euo pipefail
  pip install --quiet "huggingface_hub[cli]"
  python - <<PY
import json, subprocess, sys
for m in json.load(sys.stdin):
    dest = f"/models/{m[\"id\"]}"
    includes = [m["gguf_include"]] + ([m["mmproj_include"]] if m["mmproj_include"] else [])
    args = ["hf", "download", m["hf_repo"], "--local-dir", dest]
    for inc in includes:
        args += ["--include", inc]
    print("==>", " ".join(args), flush=True)
    subprocess.check_call(args)
PY
'

# Generate the llama-swap config: one entry per served model, each a
# llama-server (Vulkan, all layers on GPU) bound to the downloaded files.
say "Writing $MODELS_DIR/llama-swap.yaml"
echo "$MANIFEST" | docker compose run --rm -T api python - > "$MODELS_DIR/llama-swap.yaml" <<'PY'
import glob, json, sys

models = json.load(sys.stdin)
lines = ["# Generated by scripts/local-llm-setup.sh — do not edit by hand.", "models:"]
for m in models:
    base = f"/models/{m['id']}"
    # The container sees the host ./local-models at /models; resolve filenames
    # from the manifest globs against what was actually downloaded on the host.
    gguf = f"{base}/{m['gguf_include']}"
    cmd = [
        "/usr/local/bin/llama-server", "--host", "0.0.0.0", "--port", "${PORT}",
        "-m", gguf, "-ngl", "999",
    ]
    if m["mmproj_include"]:
        cmd += ["--mmproj", f"{base}/{m['mmproj_include']}"]
    lines.append(f"  {m['served_model']}:")
    lines.append("    cmd: >")
    lines.append("      " + " ".join(cmd))
lines.append("")
print("\n".join(lines))
PY

# Flip the feature on in .env (idempotent): enabled flag, gateway URL, the
# selected catalog ids as a JSON array, and the compose profile.
LOCAL_MODELS_JSON="$(printf '%s\n' "${IDS[@]}" | python3 -c 'import json,sys; print(json.dumps([l.strip() for l in sys.stdin if l.strip()]))')"
say "Enabling local hosting in .env"
sed -i '/^LOCAL_LLM_ENABLED=/d; /^LOCAL_LLM_URL=/d; /^LOCAL_MODELS=/d; /^COMPOSE_PROFILES=/d' .env
{
  echo "LOCAL_LLM_ENABLED=true"
  echo "LOCAL_LLM_URL=http://local-llm:8080/v1"
  echo "LOCAL_MODELS=$LOCAL_MODELS_JSON"
  echo "COMPOSE_PROFILES=local-llm"
} >> .env

say "Building the gateway image and starting the stack"
docker compose --profile local-llm build local-llm
docker compose --profile local-llm up -d

say "Done. Local models are now selectable in Settings → LLM. They stay OFF as"
say "defaults — route specific tasks/tiers to them from that screen."
