#!/usr/bin/env bash
# OPT-IN: provision on-box speech-to-text (whisper.cpp via its own llama-swap) and
# enable it. The audio sibling of scripts/local-llm-setup.sh / comfyui-setup.sh.
#
#   sudo bash scripts/whisper-setup.sh                 # default: large-v3-turbo
#   sudo bash scripts/whisper-setup.sh base.en         # a smaller/faster model
#   sudo bash scripts/whisper-setup.sh large-v3-turbo-q5_0   # a quantized variant
#
# NEVER run by the default install or dev-setup.sh — it downloads a GGML model and
# starts a GPU service, so it is a deliberate, separate step. It:
#   1. downloads the chosen GGML whisper model into ./whisper-models/,
#   2. writes ./whisper-models/llama-swap.yaml (the one-model gateway config —
#      whisper-server on the OpenAI audio path, idle-unloaded after `ttl`),
#   3. flips JBRAIN_WHISPER_* on in .env and starts the `whisper` compose profile.
#
# Run from the install dir (/opt/jbrain2) where docker-compose.yml + .env live.
set -euo pipefail

INSTALL_DIR="${JBRAIN_INSTALL_DIR:-/opt/jbrain2}"
MODELS_DIR="$INSTALL_DIR/whisper-models"
cd "$INSTALL_DIR"

say() { printf '\n[whisper] %s\n' "$*"; }

# Serialize runs — two concurrent provisions race on the same download dir.
exec 9>"$INSTALL_DIR/.whisper-setup.lock"
if ! flock -n 9; then
  echo "[whisper] another whisper-setup run is already in progress — aborting." >&2
  exit 1
fi

# Give the download container a stable name and force-remove it on ANY exit, so a
# Ctrl+C can't strand it holding the HF download lock for the next run.
DOWNLOAD_CONTAINER="jbrain-whisper-download"
cleanup() { docker rm -f "$DOWNLOAD_CONTAINER" >/dev/null 2>&1 || true; }
trap cleanup EXIT INT TERM

[ -f .env ] || { echo "No .env in $INSTALL_DIR — run deploy/install.sh first." >&2; exit 1; }

# The model id maps to the official GGML filename ggml-<id>.bin in the
# ggerganov/whisper.cpp HF repo (e.g. large-v3-turbo, base.en, small, medium,
# large-v3-turbo-q5_0). The served-model name stays the generic "whisper" so the
# app's unload (JBRAIN_WHISPER_MODEL) is stable across a model swap.
MODEL_ID="${1:-large-v3-turbo}"
GGML_FILE="ggml-${MODEL_ID}.bin"
say "Selected model: ${MODEL_ID} (${GGML_FILE})"

# Vulkan on gfx1151 needs only the render node (not /dev/kfd). Warn, don't block.
[ -e /dev/dri ] || say "WARNING: /dev/dri not found — Vulkan whisper needs an AMD GPU. Continuing anyway."

# gfx1151 needs kernel >= 6.18.4 (older has a known stability bug). Warn only.
KREL="$(uname -r)"
if [ "$(printf '6.18.4\n%s\n' "${KREL%%-*}" | sort -V | head -1)" != "6.18.4" ]; then
  say "WARNING: kernel $KREL is older than 6.18.4 — gfx1151 has a stability bug below that."
fi

# large-v3-turbo is ~1.6 GB; warn (don't block) if the install disk looks tight.
AVAIL_GB="$(df -BG --output=avail "$INSTALL_DIR" | tail -1 | tr -dc '0-9')"
if [ -n "$AVAIL_GB" ] && [ "$AVAIL_GB" -lt 5 ]; then
  say "WARNING: only ${AVAIL_GB} GB free on $INSTALL_DIR — a large model needs a few GB."
fi

mkdir -p "$MODELS_DIR"

# Download the GGML model with the official huggingface_hub CLI in a throwaway
# container. Idempotent: hf skips a file already present, so re-runs cost nothing.
if [ -f "$MODELS_DIR/$GGML_FILE" ]; then
  say "Model already present at $MODELS_DIR/$GGML_FILE — skipping download"
else
  say "Downloading $GGML_FILE into $MODELS_DIR (this can take a while)"
  TTY_FLAG=""
  [ -t 1 ] && TTY_FLAG="-t"
  docker run --rm $TTY_FLAG --name "$DOWNLOAD_CONTAINER" \
    -e GGML_FILE="$GGML_FILE" -v "$MODELS_DIR:/models" python:3.11-slim bash -c '
    set -euo pipefail
    pip install --quiet -U "huggingface_hub[cli]"
    hf download ggerganov/whisper.cpp "$GGML_FILE" --local-dir /tmp/hf_stage
    cp "/tmp/hf_stage/$GGML_FILE" "/models/$GGML_FILE"
  '
fi
[ -f "$MODELS_DIR/$GGML_FILE" ] || { echo "[whisper] download failed — no $GGML_FILE." >&2; exit 1; }

# Write the one-model llama-swap config. The gateway loads whisper-server on the
# first request and frees it after `ttl` idle (and the app unloads it explicitly
# after each call). --inference-path puts whisper-server's transcription handler on
# the OpenAI path llama-swap proxies to. --convert asks whisper-server to transcode
# non-WAV audio (mp3/m4a/ogg/…) via ffmpeg; if the image lacks the ffmpeg binary,
# only WAV transcribes and other formats error — drop the flag (or pre-transcode)
# in that case. The served name is the generic "whisper" (JBRAIN_WHISPER_MODEL), so
# a model swap needs no app config change.
say "Writing $MODELS_DIR/llama-swap.yaml"
cat > "$MODELS_DIR/llama-swap.yaml" <<EOF
# Generated by scripts/whisper-setup.sh — do not edit by hand.
# Generous cold-load window for the CPU model load (the image's sample uses this too).
healthCheckTimeout: 300
models:
  whisper:
    proxy: http://127.0.0.1:9200
    # whisper-server isn't a llama-server, so llama-swap's default /health probe
    # doesn't gate it; poll GET / (returns 200) until the model finishes loading
    # before forwarding — the same readiness gate the image's sample uses for its
    # sd-server model. Without it llama-swap proxies into the not-yet-bound port
    # during the ~10s CPU load and the first request fails with "connection refused".
    checkEndpoint: /
    cmd: >
      whisper-server --host 127.0.0.1 --port 9200
      --model /models/${GGML_FILE}
      --inference-path /v1/audio/transcriptions
      --convert
    ttl: 300
EOF

# The gateway container must join the HOST's video/render GIDs to open
# /dev/dri/renderD128. Prefer the device's actual owning GID; fall back to names.
RENDER_GID="$(stat -c %g /dev/dri/renderD128 2>/dev/null || getent group render | cut -d: -f3 || true)"
VIDEO_GID="$(getent group video | cut -d: -f3 || true)"
if [ -z "$RENDER_GID" ] && [ -z "$VIDEO_GID" ]; then
  say "WARNING: could not resolve a render/video GID — the gateway may be denied /dev/dri."
fi

# Flip the feature on in .env (idempotent): enabled flag, gateway URL, served-model
# name, and the GPU GIDs (shared with the local-llm/comfyui gateways). We do NOT
# persist COMPOSE_PROFILES — the `jbrain` helper activates the whisper profile from
# WHISPER_ENABLED so the service isn't dragged into unrelated commands.
say "Enabling transcription in .env"
sed -i '/^WHISPER_ENABLED=/d; /^WHISPER_URL=/d; /^WHISPER_MODEL=/d; /^VIDEO_GID=/d; /^RENDER_GID=/d' .env
{
  echo "WHISPER_ENABLED=true"
  echo "WHISPER_URL=http://whisper:8080/v1"
  echo "WHISPER_MODEL=whisper"
  [ -n "$VIDEO_GID" ] && echo "VIDEO_GID=$VIDEO_GID"
  [ -n "$RENDER_GID" ] && echo "RENDER_GID=$RENDER_GID"
} >> .env

say "Building the whisper image (compiles whisper.cpp's server) and starting it"
docker compose --profile whisper build whisper
docker compose --profile whisper up -d whisper
# Recreate the api + worker so they pick up the new JBRAIN_WHISPER_* env (audio
# attachments now transcribe and jerv gains the transcribe tool).
docker compose up -d api worker

say "Done. Audio note attachments are transcribed and indexed, and jerv can"
say "transcribe an attached audio file. The model loads on first use (one-time"
say "load) and is freed when idle — the first transcription pays the load."
