"""Generate the llama-swap gateway config (llama-swap.yaml).

The single source of truth for the gateway's per-model `llama-server` command —
crucially the `-c` context window, which must equal what the router reports to the
PWA's context meter (jbrain.llm.router.context_window). Two callers share it so the
two never drift:

  - scripts/local-llm-setup.sh, at install time, via `python -m
    jbrain.llm.llama_swap_config <models_dir>` reading the MANIFEST env;
  - the settings API, at runtime, to re-stamp a model's `-c` after the operator
    edits its context window — written atomically into the mounted models dir,
    which the gateway (run with `--watch-config`) hot-reloads. A `-c` change takes
    effect on the model's next (re)load, so the API unloads a resident model after
    rewriting so its next request reloads at the new window.

Each manifest entry is a catalog dict (jbrain.llm.local_catalog.LocalModel
asdict): id, served_model, gguf_include, mmproj_include, context_window,
recommended. `windows` overrides a model's `-c` by catalog id.
"""

from __future__ import annotations

import glob
import json
import os
import sys
from collections.abc import Mapping, Sequence
from typing import cast

# Concrete, distinct upstream ports — llama-swap's ${PORT} macro isn't substituted
# by every build, and the resident group runs models concurrently so they can't
# share a port. 127.0.0.1: llama-swap and llama-server share the container.
UPSTREAM_PORT_BASE = 9100

_TRUTHY = ("1", "true", "yes", "on")


def resolve_weight(root: str, model_id: str, pattern: str) -> str:
    """The weight path (RELATIVE to the model dir) for a model's glob — the first
    shard for a multi-part GGUF (llama.cpp follows it to the rest). Raises if
    nothing matches or a shard set is incomplete, so a partial download fails here,
    not cryptically at gateway load.

    Searches recursively: some repos (Unsloth's UD-Q* quants) nest the shards in a
    quant subdirectory, so `hf download` saves them under `<id>/<quant>/`. The
    return value is relative to `<root>/<id>` (a bare filename at the top level, or
    `<quant>/<file>` when nested) so the gateway's `-m /models/<id>/<rel>` resolves
    either way. hf's `.cache/` download-staging dir is skipped."""
    base = os.path.join(root, model_id)
    matches = sorted(
        m
        for m in glob.glob(os.path.join(base, "**", pattern), recursive=True)
        if ".cache" not in os.path.relpath(m, base).split(os.sep)
    )
    if not matches:
        raise FileNotFoundError(
            f"no file matching {pattern!r} for {model_id} under {root} — download incomplete?"
        )
    rels = [os.path.relpath(m, base) for m in matches]
    shards = [r for r in rels if "-00001-of-" in os.path.basename(r)]
    if shards:
        first = shards[0]
        total = int(os.path.basename(first).split("-of-")[1].split(".gguf")[0])
        if len(matches) != total:
            raise FileNotFoundError(
                f"{model_id}: expected {total} shards for {pattern!r}, found {len(matches)}"
            )
        return first
    return rels[0]


def render(
    models: Sequence[Mapping[str, object]],
    root: str,
    *,
    windows: Mapping[str, int] | None = None,
    resident_group: bool = False,
) -> str:
    """The full llama-swap.yaml text for `models` (catalog manifest dicts). `root`
    is the host path to the weights (globbed to resolve filenames); `windows` maps
    catalog id → context-window override (absent = the model's catalog default)."""
    windows = windows or {}
    lines = ["# Generated by jbrain.llm.llama_swap_config — do not edit by hand.", "models:"]
    for i, m in enumerate(models):
        port = UPSTREAM_PORT_BASE + i
        model_id = str(m["id"])
        gguf = resolve_weight(root, model_id, str(m["gguf_include"]))
        window = windows.get(model_id, int(cast(int, m["context_window"])))
        cmd = [
            "llama-server",
            "--host",
            "127.0.0.1",
            "--port",
            str(port),
            # The context window. Must match what the router reports to the meter.
            "-c",
            str(window),
            # Tool calling needs the model's own chat template: --jinja makes
            # llama-server render the embedded (Hermes-style for Qwen) tool-use
            # template and parse `<tool_call>` blocks back into structured
            # `tool_calls`. Without it the OpenAI `tools` we send have no grammar
            # behind them and the model free-forms text (a narrated, never-called
            # image) — so the on-box image tools never fire.
            "--jinja",
            # gfx1151 stability/perf flags: flash attention + --no-mmap; -ngl 999
            # offloads every layer to the iGPU.
            "-fa",
            "1",
            "--no-mmap",
            "-m",
            f"/models/{model_id}/{gguf}",
            "-ngl",
            "999",
        ]
        mmproj = m.get("mmproj_include")
        if mmproj:
            cmd += ["--mmproj", f"/models/{model_id}/{resolve_weight(root, model_id, str(mmproj))}"]
        lines.append(f"  {m['served_model']}:")
        lines.append(f"    proxy: http://127.0.0.1:{port}")
        lines.append("    cmd: >")
        lines.append("      " + " ".join(cmd))

    # An opt-in non-swapping group keeps the recommended set co-resident (hot paths
    # skip the cold-load on task switch); off by default — every model swappable.
    resident = [str(m["served_model"]) for m in models if m.get("recommended")]
    if resident_group and len(resident) > 1:
        lines.append("groups:")
        lines.append("  resident:")
        lines.append("    swap: false")
        lines.append("    exclusive: false")
        lines.append("    members:")
        lines += [f"      - {name}" for name in resident]

    return "\n".join(lines) + "\n"


def write(
    root: str,
    models: Sequence[Mapping[str, object]],
    *,
    windows: Mapping[str, int] | None = None,
    resident_group: bool = False,
) -> str:
    """Render and atomically write {root}/llama-swap.yaml (temp + rename so the
    gateway's --watch-config never sees a half-written file). Returns the path."""
    text = render(models, root, windows=windows, resident_group=resident_group)
    path = os.path.join(root, "llama-swap.yaml")
    tmp = f"{path}.tmp"
    with open(tmp, "w") as f:
        f.write(text)
    os.replace(tmp, path)
    return path


def _main(argv: list[str]) -> int:
    """CLI for scripts/local-llm-setup.sh: `... <models_dir>` reads the MANIFEST
    env (catalog JSON) and LOCAL_LLM_RESIDENT_GROUP, writes the config."""
    if len(argv) != 1:
        print("usage: python -m jbrain.llm.llama_swap_config <models_dir>", file=sys.stderr)
        return 2
    root = argv[0]
    models = json.loads(os.environ["MANIFEST"])
    resident = os.environ.get("LOCAL_LLM_RESIDENT_GROUP", "").strip().lower() in _TRUTHY
    path = write(root, models, resident_group=resident)
    kept = len([m for m in models if m.get("recommended")]) if resident else 0
    print(f"wrote {path}: {len(models)} model(s); {kept} kept resident (all swappable otherwise)")
    return 0


if __name__ == "__main__":
    raise SystemExit(_main(sys.argv[1:]))
