"""Generate the llama-swap gateway config (llama-swap.yaml).

The single source of truth for the gateway's per-model `llama-server` command —
crucially the `-c` context window, which must equal what the router reports to the
PWA's context meter (jbrain.llm.router.context_window). Two callers share it so the
two never drift:

  - scripts/local-llm-setup.sh, at install time, via `python -m
    jbrain.llm.llama_swap_config <models_dir>` reading the MANIFEST env;
  - the settings API, at runtime, to re-stamp a model's `-c` after the operator
    edits its context window — written atomically into the mounted models dir,
    which the gateway (run with `--watch-config`) hot-reloads. A `-c` change takes
    effect on the model's next (re)load, so the API unloads a resident model after
    rewriting so its next request reloads at the new window.

Every model joins a single non-swapping group (`swap: false`), so llama-swap never
evicts one to load another — the app (jbrain.llm.residency) is the sole evictor,
freeing the fewest models to hold a free-RAM floor before each load. `exclusive:
false` lets an on-demand request still load a member.

Each manifest entry is a catalog dict (jbrain.llm.local_catalog.LocalModel
asdict): id, served_model, gguf_include, mmproj_include, context_window,
recommended. `windows` overrides a model's `-c` by catalog id.
"""

from __future__ import annotations

import glob
import json
import os
import sys
from collections.abc import Mapping, Sequence
from typing import cast

# Concrete, distinct upstream ports — llama-swap's ${PORT} macro isn't substituted
# by every build, and the non-swapping group runs models concurrently so they can't
# share a port. 127.0.0.1: llama-swap and llama-server share the container.
UPSTREAM_PORT_BASE = 9100


def resolve_weight(root: str, model_id: str, pattern: str) -> str:
    """The weight path (RELATIVE to the model dir) for a model's glob — the first
    shard for a multi-part GGUF (llama.cpp follows it to the rest). Raises if
    nothing matches or a shard set is incomplete, so a partial download fails here,
    not cryptically at gateway load.

    Searches recursively: some repos (Unsloth's UD-Q* quants) nest the shards in a
    quant subdirectory, so `hf download` saves them under `<id>/<quant>/`. The
    return value is relative to `<root>/<id>` (a bare filename at the top level, or
    `<quant>/<file>` when nested) so the gateway's `-m /models/<id>/<rel>` resolves
    either way. hf's `.cache/` download-staging dir is skipped."""
    base = os.path.join(root, model_id)
    matches = sorted(
        m
        for m in glob.glob(os.path.join(base, "**", pattern), recursive=True)
        if ".cache" not in os.path.relpath(m, base).split(os.sep)
    )
    if not matches:
        raise FileNotFoundError(
            f"no file matching {pattern!r} for {model_id} under {root} — download incomplete?"
        )
    rels = [os.path.relpath(m, base) for m in matches]
    shards = [r for r in rels if "-00001-of-" in os.path.basename(r)]
    if shards:
        first = shards[0]
        total = int(os.path.basename(first).split("-of-")[1].split(".gguf")[0])
        if len(matches) != total:
            raise FileNotFoundError(
                f"{model_id}: expected {total} shards for {pattern!r}, found {len(matches)}"
            )
        return first
    return rels[0]


def render(
    models: Sequence[Mapping[str, object]],
    root: str,
    *,
    windows: Mapping[str, int] | None = None,
) -> str:
    """The full llama-swap.yaml text for `models` (catalog manifest dicts). `root`
    is the host path to the weights (globbed to resolve filenames); `windows` maps
    catalog id → context-window override (absent = the model's catalog default).
    Every model joins one `swap: false` group so the gateway never auto-evicts — the
    app is the sole evictor (jbrain.llm.residency)."""
    windows = windows or {}
    lines = ["# Generated by jbrain.llm.llama_swap_config — do not edit by hand.", "models:"]
    for i, m in enumerate(models):
        port = UPSTREAM_PORT_BASE + i
        model_id = str(m["id"])
        gguf = resolve_weight(root, model_id, str(m["gguf_include"]))
        window = windows.get(model_id, int(cast(int, m["context_window"])))
        cmd = [
            "llama-server",
            "--host",
            "127.0.0.1",
            "--port",
            str(port),
            # The context window. Must match what the router reports to the meter.
            "-c",
            str(window),
            # Tool calling needs the model's own chat template: --jinja makes
            # llama-server render the embedded (Hermes-style for Qwen) tool-use
            # template and parse `<tool_call>` blocks back into structured
            # `tool_calls`. Without it the OpenAI `tools` we send have no grammar
            # behind them and the model free-forms text (a narrated, never-called
            # image) — so the on-box image tools never fire.
            "--jinja",
            # gfx1151 stability/perf flags: flash attention + --no-mmap; -ngl 999
            # offloads every layer to the iGPU.
            "-fa",
            "1",
            "--no-mmap",
            # Prompt-prefix KV reuse (docs/plans/LLM_PROMPT_CACHE_PLAN.md W2): keep the KV of
            # a matching leading prefix and salvage it via KV-shifting even after a later
            # divergence, so a stable system-prompt + history prefix isn't re-prefilled every
            # turn (the "slow first token"). 256 is the min chunk size worth reusing. Pairs
            # with W1's cache-stable message layout. A long-standing llama.cpp server flag.
            "--cache-reuse",
            "256",
            "-m",
            f"/models/{model_id}/{gguf}",
            "-ngl",
            "999",
        ]
        # A thinking model emits its reasoning inline as `<think>…</think>`;
        # `--reasoning-format deepseek` (paired with --jinja above) makes llama.cpp parse
        # those tags out of `content` into the `reasoning_content` channel the shim maps to
        # Anthropic thinking blocks. Empty (the common case) leaves llama.cpp's `auto`.
        reasoning_format = str(m.get("reasoning_format") or "")
        if reasoning_format:
            cmd += ["--reasoning-format", reasoning_format]
        mmproj = m.get("mmproj_include")
        if mmproj:
            cmd += ["--mmproj", f"/models/{model_id}/{resolve_weight(root, model_id, str(mmproj))}"]
        # Model-specific serving flags (e.g. the MTP variant's `--spec-type draft-mtp …`
        # self-speculative-decoding config), appended verbatim after the shared flags.
        for flag in cast("Sequence[str]", m.get("extra_server_args") or ()):
            cmd.append(str(flag))
        lines.append(f"  {m['served_model']}:")
        lines.append(f"    proxy: http://127.0.0.1:{port}")
        lines.append("    cmd: >")
        lines.append("      " + " ".join(cmd))

    # One non-swapping group with EVERY model as a member: `swap: false` means llama-swap
    # never evicts a member to load another, and `exclusive: false` lets an on-demand request
    # still load one. So the gateway never auto-evicts — the app (jbrain.llm.residency) is the
    # sole evictor, freeing the fewest models to hold the free-RAM floor before each load. This
    # replaced the old all-or-nothing pin (recommended pair ≈ 91 GB, no headroom) that
    # hard-locked the host; the app's budget is what keeps it safe.
    resident = [str(m["served_model"]) for m in models]
    if resident:
        lines.append("groups:")
        lines.append("  resident:")
        lines.append("    swap: false")
        lines.append("    exclusive: false")
        lines.append("    members:")
        lines += [f"      - {name}" for name in resident]

    return "\n".join(lines) + "\n"


def write(
    root: str,
    models: Sequence[Mapping[str, object]],
    *,
    windows: Mapping[str, int] | None = None,
) -> str:
    """Render and atomically write {root}/llama-swap.yaml (temp + rename so the
    gateway's --watch-config never sees a half-written file). Returns the path."""
    text = render(models, root, windows=windows)
    path = os.path.join(root, "llama-swap.yaml")
    tmp = f"{path}.tmp"
    with open(tmp, "w") as f:
        f.write(text)
    os.replace(tmp, path)
    return path


def _main(argv: list[str]) -> int:
    """CLI for scripts/local-llm-setup.sh: `... <models_dir>` reads the MANIFEST
    env (catalog JSON) and writes the config."""
    if len(argv) != 1:
        print("usage: python -m jbrain.llm.llama_swap_config <models_dir>", file=sys.stderr)
        return 2
    root = argv[0]
    models = json.loads(os.environ["MANIFEST"])
    path = write(root, models)
    print(f"wrote {path}: {len(models)} model(s); the app evicts to make room per load")
    return 0


if __name__ == "__main__":
    raise SystemExit(_main(sys.argv[1:]))
